In [24]:
# Code to get the data

In [25]:
import pandas as pd
import numpy as np

In [26]:
# Data Cleaning

In [27]:
df = pd.read_csv("/Users/abhaybapat/Desktop/Data Science Project/betting_classification_model/data/TeamStatistics.csv")

In [28]:
df.head()

,gameId,gameDateTimeEst,teamCity,teamName,teamId,opponentTeamCity,opponentTeamName,opponentTeamId,home,win,...,gameLabel,gameSubLabel,seriesGameNumber,seed,reboundsTeam,turnoversTeam,ot1Points,ot2Points,otAllPoints,gameDate
0,42500401,2026-06-03 20:30:00,New York,Knicks,1610612752,San Antonio,Spurs,1610612759,0,1.0,...,NBA Finals,Game 1,1.0,3.0,11.0,1.0,NaN,NaN,NaN,2026-06-03 20:30:00
1,42500401,2026-06-03 20:30:00,San Antonio,Spurs,1610612759,New York,Knicks,1610612752,1,0.0,...,NBA Finals,Game 1,1.0,2.0,6.0,0.0,NaN,NaN,NaN,2026-06-03 20:30:00
2,42500317,2026-05-30 20:00:00,San Antonio,Spurs,1610612759,Oklahoma City,Thunder,1610612760,0,1.0,...,West Conf. Finals,Game 7,7.0,2.0,10.0,0.0,NaN,NaN,NaN,2026-05-30 20:00:00
3,42500317,2026-05-30 20:00:00,Oklahoma City,Thunder,1610612760,San Antonio,Spurs,1610612759,1,0.0,...,West Conf. Finals,Game 7,7.0,1.0,18.0,1.0,NaN,NaN,NaN,2026-05-30 20:00:00
4,42500316,2026-05-28 20:30:00,Oklahoma City,Thunder,1610612760,San Antonio,Spurs,1610612759,0,0.0,...,West Conf. Finals,Game 6,6.0,1.0,9.0,1.0,NaN,NaN,NaN,2026-05-28 20:30:00

In [29]:
df.shape

(146552, 59)

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 146552 entries, 0 to 146551
Data columns (total 59 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   gameId                   146552 non-null  int64
 1   gameDateTimeEst          146552 non-null  object
 2   teamCity                 146536 non-null  object
 3   teamName                 146550 non-null  object
 4   teamId                   146552 non-null  int64
 5   opponentTeamCity         146536 non-null  object
 6   opponentTeamName         146550 non-null  object
 7   opponentTeamId           146552 non-null  int64
 8   home                     146552 non-null  int64
 9   win                      146550 non-null  float64
 10  teamScore                146552 non-null  int64
 11  opponentScore            146552 non-null  int64
 12  assists                  146548 non-null  float64
 13  blocks                   146548 non-null  float64
 14  steals                   146548 non-null  float64
 15  fieldGoalsAttempted      146548 non-null  float64
 16  fieldGoalsMade           146550 non-null  float64
 17  fieldGoalsPercentage     146548 non-null  float64
 18  threePointersAttempted   146548 non-null  float64
 19  threePointersMade        146548 non-null  float64
 20  threePointersPercentage  146547 non-null  float64
 21  freeThrowsAttempted      146548 non-null  float64
 22  freeThrowsMade           146550 non-null  float64
 23  freeThrowsPercentage     146548 non-null  float64
 24  reboundsDefensive        146548 non-null  float64
 25  reboundsOffensive        146548 non-null  float64
 26  reboundsTotal            146548 non-null  float64
 27  foulsPersonal            146548 non-null  float64
 28  turnovers                146548 non-null  float64
 29  plusMinusPoints          146495 non-null  float64
 30  numMinutes               146546 non-null  float64
 31  q1Points                 138704 non-null  float64
 32  q2Points                 138688 non-null  float64
 33  q3Points                 138654 non-null  float64
 34  q4Points                 138652 non-null  float64
 35  benchPoints              139242 non-null  float64
 36  biggestLead              139242 non-null  float64
 37  biggestScoringRun        139242 non-null  float64
 38  leadChanges              139242 non-null  float64
 39  pointsFastBreak          139242 non-null  float64
 40  pointsFromTurnovers      139242 non-null  float64
 41  pointsInThePaint         139242 non-null  float64
 42  pointsSecondChance       139242 non-null  float64
 43  timesTied                139242 non-null  float64
 44  timeoutsRemaining        139242 non-null  float64
 45  seasonWins               139242 non-null  float64
 46  seasonLosses             139242 non-null  float64
 47  coachId                  0 non-null       float64
 48  gameType                 138962 non-null  object
 49  gameLabel                9302 non-null    object
 50  gameSubLabel             9220 non-null    object
 51  seriesGameNumber         8870 non-null    float64
 52  seed                     7864 non-null    float64
 53  reboundsTeam             138962 non-null  float64
 54  turnoversTeam            138962 non-null  float64
 55  ot1Points                7816 non-null    float64
 56  ot2Points                1106 non-null    float64
 57  otAllPoints              7820 non-null    float64
 58  gameDate                 146552 non-null  object
dtypes: float64(44), int64(6), object(9)
memory usage: 66.0+ MB

In [31]:
df["gameDateTimeEst"] = pd.to_datetime(df["gameDateTimeEst"])

In [32]:
df["gameDateTimeEst"].info()

<class 'pandas.core.series.Series'>
RangeIndex: 146552 entries, 0 to 146551
Series name: gameDateTimeEst
Non-Null Count   Dtype
--------------   -----
146552 non-null  datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 1.1 MB

In [33]:
df = df.loc[df["gameDateTimeEst"] >= "2012-7-30 20:00:00"]

In [34]:
df.shape

(38492, 59)

In [35]:
df = df[(df.gameType == "Playoffs") | (df.gameType == "Regular Season")]

In [36]:
df = df.sort_values(by="gameDateTimeEst")

In [37]:
df.shape

(33494, 59)

In [38]:
hornets_teams = df[df["teamName"] == "Hornets"]
hornets_teams["teamCity"].value_counts()

teamCity
Charlotte      880
New Orleans     82
Name: count, dtype: int64

In [39]:
conditions = [
    (df['teamCity'] == 'New Orleans') & (df['teamName'] == 'Hornets'),
    (df['teamCity'] == 'Charlotte') & (df['teamName'] == 'Bobcats'),
]

new_cities = ['New Orleans', 'Charlotte']
new_names = ['Pelicans', 'Hornets']

df['teamName'] = np.select(conditions, new_names, default=df['teamName'])

In [40]:
df = df.loc[:, "gameId":"turnovers"]

In [41]:
columns_to_drop = ["teamCity", "opponentTeamCity", "opponentTeamId", "opponentTeamName"]
df = df.drop(columns=columns_to_drop)

In [42]:
df.shape

(33494, 25)

In [43]:
df.isna().sum()

gameId                     0
gameDateTimeEst            0
teamName                   0
teamId                     0
home                       0
win                        0
teamScore                  0
opponentScore              0
assists                    0
blocks                     0
steals                     0
fieldGoalsAttempted        0
fieldGoalsMade             0
fieldGoalsPercentage       0
threePointersAttempted     0
threePointersMade          0
threePointersPercentage    0
freeThrowsAttempted        0
freeThrowsMade             0
freeThrowsPercentage       0
reboundsDefensive          0
reboundsOffensive          0
reboundsTotal              0
foulsPersonal              0
turnovers                  0
dtype: int64

In [44]:
df.teamName.value_counts()

teamName
Warriors         1188
Celtics          1186
Heat             1166
Thunder          1165
Cavaliers        1164
Spurs            1152
Pacers           1150
Clippers         1148
Nuggets          1148
Rockets          1143
Raptors          1139
Bucks            1133
Trail Blazers    1115
Hawks            1115
Knicks           1114
76ers            1113
Lakers           1111
Grizzlies        1105
Mavericks        1101
Nets             1096
Jazz             1091
Wizards          1091
Timberwolves     1091
Suns             1088
Magic            1076
Bulls            1074
Pistons          1068
Pelicans         1062
Kings            1053
Hornets          1048
Name: count, dtype: int64

In [45]:
df = df.rename(columns={"teamScore": "points"})

In [46]:
df

,gameId,gameDateTimeEst,teamName,teamId,home,win,points,opponentScore,assists,blocks,...,threePointersMade,threePointersPercentage,freeThrowsAttempted,freeThrowsMade,freeThrowsPercentage,reboundsDefensive,reboundsOffensive,reboundsTotal,foulsPersonal,turnovers
38279,21200001,2012-10-30 19:00:00,Cavaliers,1610612739,1,1.0,94,84,22.0,5.0,...,7.0,0.350,22.0,15.0,0.682,36.0,18.0,54.0,21.0,21.0
38278,21200001,2012-10-30 19:00:00,Wizards,1610612764,0,0.0,84,94,26.0,10.0,...,8.0,0.250,20.0,12.0,0.600,21.0,18.0,39.0,19.0,13.0
38276,21200002,2012-10-30 20:00:00,Heat,1610612748,1,1.0,120,107,25.0,5.0,...,8.0,0.500,32.0,26.0,0.813,31.0,5.0,36.0,20.0,8.0
38277,21200002,2012-10-30 20:00:00,Celtics,1610612738,0,0.0,107,120,24.0,2.0,...,6.0,0.462,28.0,23.0,0.821,34.0,7.0,41.0,23.0,16.0
38274,21200003,2012-10-30 22:30:00,Mavericks,1610612742,0,1.0,99,91,22.0,5.0,...,5.0,0.333,18.0,14.0,0.778,31.0,9.0,40.0,25.0,12.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,42500316,2026-05-28 20:30:00,Thunder,1610612760,0,0.0,91,118,22.0,3.0,...,10.0,0.250,12.0,11.0,0.917,30.0,12.0,42.0,21.0,12.0
3,42500317,2026-05-30 20:00:00,Thunder,1610612760,1,0.0,103,111,23.0,5.0,...,12.0,0.343,22.0,17.0,0.773,28.0,10.0,38.0,16.0,13.0
2,42500317,2026-05-30 20:00:00,Spurs,1610612759,0,1.0,111,103,21.0,2.0,...,17.0,0.425,19.0,14.0,0.737,25.0,15.0,40.0,18.0,12.0
1,42500401,2026-06-03 20:30:00,Spurs,1610612759,1,0.0,95,105,16.0,4.0,...,11.0,0.256,25.0,20.0,0.800,40.0,14.0,54.0,23.0,13.0
0,42500401,2026-06-03 20:30:00,Knicks,1610612752,0,1.0,105,95,20.0,4.0,...,11.0,0.306,18.0,16.0,0.889,39.0,10.0,49.0,23.0,8.0

In [47]:
df

,gameId,gameDateTimeEst,teamName,teamId,home,win,points,opponentScore,assists,blocks,...,threePointersMade,threePointersPercentage,freeThrowsAttempted,freeThrowsMade,freeThrowsPercentage,reboundsDefensive,reboundsOffensive,reboundsTotal,foulsPersonal,turnovers
38279,21200001,2012-10-30 19:00:00,Cavaliers,1610612739,1,1.0,94,84,22.0,5.0,...,7.0,0.350,22.0,15.0,0.682,36.0,18.0,54.0,21.0,21.0
38278,21200001,2012-10-30 19:00:00,Wizards,1610612764,0,0.0,84,94,26.0,10.0,...,8.0,0.250,20.0,12.0,0.600,21.0,18.0,39.0,19.0,13.0
38276,21200002,2012-10-30 20:00:00,Heat,1610612748,1,1.0,120,107,25.0,5.0,...,8.0,0.500,32.0,26.0,0.813,31.0,5.0,36.0,20.0,8.0
38277,21200002,2012-10-30 20:00:00,Celtics,1610612738,0,0.0,107,120,24.0,2.0,...,6.0,0.462,28.0,23.0,0.821,34.0,7.0,41.0,23.0,16.0
38274,21200003,2012-10-30 22:30:00,Mavericks,1610612742,0,1.0,99,91,22.0,5.0,...,5.0,0.333,18.0,14.0,0.778,31.0,9.0,40.0,25.0,12.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,42500316,2026-05-28 20:30:00,Thunder,1610612760,0,0.0,91,118,22.0,3.0,...,10.0,0.250,12.0,11.0,0.917,30.0,12.0,42.0,21.0,12.0
3,42500317,2026-05-30 20:00:00,Thunder,1610612760,1,0.0,103,111,23.0,5.0,...,12.0,0.343,22.0,17.0,0.773,28.0,10.0,38.0,16.0,13.0
2,42500317,2026-05-30 20:00:00,Spurs,1610612759,0,1.0,111,103,21.0,2.0,...,17.0,0.425,19.0,14.0,0.737,25.0,15.0,40.0,18.0,12.0
1,42500401,2026-06-03 20:30:00,Spurs,1610612759,1,0.0,95,105,16.0,4.0,...,11.0,0.256,25.0,20.0,0.800,40.0,14.0,54.0,23.0,13.0
0,42500401,2026-06-03 20:30:00,Knicks,1610612752,0,1.0,105,95,20.0,4.0,...,11.0,0.306,18.0,16.0,0.889,39.0,10.0,49.0,23.0,8.0

In [48]:
# Calculate single game features

In [49]:
def shift_opponent_stats(df):
    df = df.sort_values(by=["gameDateTimeEst", "gameId", "home"])

    opp_map = df[["gameId", "home", "reboundsDefensive"]].copy()
    
    opp_map["home"] = opp_map["home"].replace({1: 0, 0: 1})
    
    opp_map = opp_map.rename(columns={
        "reboundsDefensive": "opp_dreb"
    })
    
    df = pd.merge(df, opp_map, on=["gameId", "home"], how="left")

    return df

In [50]:
def create_four_factors(df):

    df["possessions"] = .96 * (df["fieldGoalsAttempted"] + df["turnovers"] + .44 * df["freeThrowsAttempted"] - df["reboundsOffensive"])

    df["eFG"] = (df["fieldGoalsMade"] + .5 * df["threePointersMade"]) / df["fieldGoalsAttempted"]

    df["TO%"] = df["turnovers"] / df["possessions"]

    df["OREB%"] = (df["reboundsOffensive"]) / (df["reboundsOffensive"] + df["opp_dreb"])

    df["FTR"] = df["freeThrowsAttempted"] / df["fieldGoalsAttempted"]

    df = df.drop(columns=df.loc[:,"assists":"opp_dreb"].columns)

    return df

In [51]:
def team_rating(df):
    df["off_rating"] = (df["points"] / df["possessions"]) * 100
    df["def_rating"] = (df["opponentScore"] / df["possessions"]) * 100
    df["net_rating"] = df["off_rating"] - df["def_rating"]
    return df

In [52]:
df = shift_opponent_stats(df)
df = create_four_factors(df)
df = team_rating(df)

In [53]:
df

,gameId,gameDateTimeEst,teamName,teamId,home,win,points,opponentScore,possessions,eFG,TO%,OREB%,FTR,off_rating,def_rating,net_rating
0,21200001,2012-10-30 19:00:00,Wizards,1610612764,0,0.0,84,94,90.0480,0.400000,0.144367,0.333333,0.222222,93.283582,104.388770,-11.105188
1,21200001,2012-10-30 19:00:00,Cavaliers,1610612739,1,1.0,94,84,88.0128,0.500000,0.238602,0.461538,0.278481,106.802647,95.440663,11.361984
2,21200002,2012-10-30 20:00:00,Celtics,1610612738,0,0.0,107,120,92.4672,0.560000,0.173034,0.184211,0.373333,115.716708,129.775748,-14.059039
3,21200002,2012-10-30 20:00:00,Heat,1610612748,1,1.0,120,107,92.2368,0.594937,0.086733,0.128205,0.405063,130.099917,116.005759,14.094158
4,21200003,2012-10-30 22:30:00,Mavericks,1610612742,0,1.0,99,91,92.0832,0.500000,0.130317,0.225000,0.211765,107.511468,98.823673,8.687795
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33489,42500316,2026-05-28 20:30:00,Spurs,1610612759,1,1.0,118,91,96.0000,0.551136,0.125000,0.268293,0.284091,122.916667,94.791667,28.125000
33490,42500317,2026-05-30 20:00:00,Spurs,1610612759,0,1.0,111,103,89.6256,0.551136,0.133890,0.348837,0.215909,123.848543,114.922522,8.926021
33491,42500317,2026-05-30 20:00:00,Thunder,1610612760,1,0.0,103,111,91.8528,0.518072,0.141531,0.285714,0.265060,112.135939,120.845527,-8.709588
33492,42500401,2026-06-03 20:30:00,Knicks,1610612752,0,1.0,105,95,95.9232,0.473404,0.083400,0.200000,0.191489,109.462570,99.037563,10.425007
33493,42500401,2026-06-03 20:30:00,Spurs,1610612759,1,0.0,95,105,95.0400,0.421348,0.136785,0.264151,0.280899,99.957912,110.479798,-10.521886

In [54]:
# Calculate elo for each team

In [55]:
raw_elo_df = pd.read_csv("/Users/abhaybapat/Desktop/Data Science Project/betting_classification_model/data/nbaallelo.csv")

In [56]:
raw_elo_df.head()

,gameorder,game_id,lg_id,_iscopy,year_id,date_game,seasongame,is_playoffs,team_id,fran_id,...,win_equiv,opp_id,opp_fran,opp_pts,opp_elo_i,opp_elo_n,game_location,game_result,forecast,notes
0,1,194611010TRH,NBA,0,1947,11/1/1946,1,0,TRH,Huskies,...,40.294830,NYK,Knicks,68,1300.0000,1306.7233,H,L,0.640065,NaN
1,1,194611010TRH,NBA,1,1947,11/1/1946,1,0,NYK,Knicks,...,41.705170,TRH,Huskies,66,1300.0000,1293.2767,A,W,0.359935,NaN
2,2,194611020CHS,NBA,0,1947,11/2/1946,1,0,CHS,Stags,...,42.012257,NYK,Knicks,47,1306.7233,1297.0712,H,W,0.631101,NaN
3,2,194611020CHS,NBA,1,1947,11/2/1946,2,0,NYK,Knicks,...,40.692783,CHS,Stags,63,1300.0000,1309.6521,A,L,0.368899,NaN
4,3,194611020DTF,NBA,0,1947,11/2/1946,1,0,DTF,Falcons,...,38.864048,WSC,Capitols,50,1300.0000,1320.3811,H,L,0.640065,NaN

In [57]:
raw_elo_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 126314 entries, 0 to 126313
Data columns (total 23 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   gameorder      126314 non-null  int64
 1   game_id        126314 non-null  object
 2   lg_id          126314 non-null  object
 3   _iscopy        126314 non-null  int64
 4   year_id        126314 non-null  int64
 5   date_game      126314 non-null  object
 6   seasongame     126314 non-null  int64
 7   is_playoffs    126314 non-null  int64
 8   team_id        126314 non-null  object
 9   fran_id        126314 non-null  object
 10  pts            126314 non-null  int64
 11  elo_i          126314 non-null  float64
 12  elo_n          126314 non-null  float64
 13  win_equiv      126314 non-null  float64
 14  opp_id         126314 non-null  object
 15  opp_fran       126314 non-null  object
 16  opp_pts        126314 non-null  int64
 17  opp_elo_i      126314 non-null  float64
 18  opp_elo_n      126314 non-null  float64
 19  game_location  126314 non-null  object
 20  game_result    126314 non-null  object
 21  forecast       126314 non-null  float64
 22  notes          5424 non-null    object
dtypes: float64(6), int64(7), object(10)
memory usage: 22.2+ MB

In [58]:
raw_elo_df["date_game"] = pd.to_datetime(raw_elo_df["date_game"])

In [59]:
elo_df = raw_elo_df[(raw_elo_df["date_game"] >= "10/29/2012") & (raw_elo_df["date_game"] <= "6/21/2013")]

In [60]:
first_game_elo_df = elo_df.drop_duplicates(subset=["fran_id"], keep="first")[["fran_id", "elo_i"]]

In [61]:
first_game_elo_df["fran_id"].sort_values().unique()

array(['Bucks', 'Bulls', 'Cavaliers', 'Celtics', 'Clippers', 'Grizzlies',
       'Hawks', 'Heat', 'Hornets', 'Jazz', 'Kings', 'Knicks', 'Lakers',
       'Magic', 'Mavericks', 'Nets', 'Nuggets', 'Pacers', 'Pelicans',
       'Pistons', 'Raptors', 'Rockets', 'Sixers', 'Spurs', 'Suns',
       'Thunder', 'Timberwolves', 'Trailblazers', 'Warriors', 'Wizards'],
      dtype=object)

In [62]:
first_game_elo_df["fran_id"] = first_game_elo_df["fran_id"].replace({"Sixers":"76ers","Trailblazers":"Trail Blazers"})

In [63]:
first_game_elo_df["fran_id"].sort_values().unique()

array(['76ers', 'Bucks', 'Bulls', 'Cavaliers', 'Celtics', 'Clippers',
       'Grizzlies', 'Hawks', 'Heat', 'Hornets', 'Jazz', 'Kings', 'Knicks',
       'Lakers', 'Magic', 'Mavericks', 'Nets', 'Nuggets', 'Pacers',
       'Pelicans', 'Pistons', 'Raptors', 'Rockets', 'Spurs', 'Suns',
       'Thunder', 'Timberwolves', 'Trail Blazers', 'Warriors', 'Wizards'],
      dtype=object)

In [64]:
df["teamName"].sort_values().unique()

array(['76ers', 'Bucks', 'Bulls', 'Cavaliers', 'Celtics', 'Clippers',
       'Grizzlies', 'Hawks', 'Heat', 'Hornets', 'Jazz', 'Kings', 'Knicks',
       'Lakers', 'Magic', 'Mavericks', 'Nets', 'Nuggets', 'Pacers',
       'Pelicans', 'Pistons', 'Raptors', 'Rockets', 'Spurs', 'Suns',
       'Thunder', 'Timberwolves', 'Trail Blazers', 'Warriors', 'Wizards'],
      dtype=object)

In [65]:
first_game_elo_df

              fran_id      elo_i
118426        Wizards  1450.8339
118427      Cavaliers  1346.9901
118428         Lakers  1555.7339
118429      Mavericks  1519.9543
118430        Celtics  1592.0532
118431           Heat  1660.3782
118432          Kings  1417.2316
118433          Bulls  1596.7417
118434        Pistons  1430.9758
118435        Rockets  1501.2556
118436      Grizzlies  1578.9830
118437       Clippers  1560.9281
118438          Spurs  1676.2136
118439       Pelicans  1453.0475
118440          76ers  1537.5059
118441        Nuggets  1576.3953
118442           Suns  1530.1812
118443       Warriors  1421.1807
118444  Trail Blazers  1450.6614
118446         Pacers  1561.7098
118447        Raptors  1437.3424
118449           Jazz  1532.3057
118451        Thunder  1659.1300
118453          Hawks  1545.6381
118455          Bucks  1501.1670
118456        Hornets  1240.0372
118465   Timberwolves  1411.7732
118468         Knicks  1529.6180
118472          Magic  1478.0159
118477           Nets  1371.4310

In [66]:
starting_elo = dict(zip(first_game_elo_df["fran_id"],first_game_elo_df["elo_i"]))

In [67]:
starting_elo

{'Wizards': 1450.8339,
 'Cavaliers': 1346.9901,
 'Lakers': 1555.7339,
 'Mavericks': 1519.9543,
 'Celtics': 1592.0532,
 'Heat': 1660.3782,
 'Kings': 1417.2316,
 'Bulls': 1596.7417,
 'Pistons': 1430.9758,
 'Rockets': 1501.2556,
 'Grizzlies': 1578.983,
 'Clippers': 1560.9281,
 'Spurs': 1676.2136,
 'Pelicans': 1453.0475,
 '76ers': 1537.5059,
 'Nuggets': 1576.3953,
 'Suns': 1530.1812,
 'Warriors': 1421.1807,
 'Trail Blazers': 1450.6614,
 'Pacers': 1561.7098,
 'Raptors': 1437.3424,
 'Jazz': 1532.3057,
 'Thunder': 1659.13,
 'Hawks': 1545.6381,
 'Bucks': 1501.167,
 'Hornets': 1240.0372,
 'Timberwolves': 1411.7732,
 'Knicks': 1529.618,
 'Magic': 1478.0159,
 'Nets': 1371.431}

In [68]:
starting_elo_df = pd.DataFrame(starting_elo, index=[0])

In [69]:
starting_elo_df.to_csv("starting_elo.csv", index=False)

In [70]:
df.to_csv("cleaned_data.csv")